project '123.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
platform:ios, ‘7.0’
 


target '123' do
pod 'PromiseKit'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 123

end
